---
- name: Install the latest version of htop, nano, and crictl
  ansible.builtin.dnf:
    name:
      - nano
    state: latest
  when: ansible_os_family == "RedHat"

- name: Remove zram from system
  ansible.builtin.dnf:
    name:
      - zram-generator-defaults
    state: absent
  when: ansible_os_family == "RedHat"
  register: zramgen

- name: Reboot the systems
  ansible.builtin.reboot:
  when: zramgen.changed

- name: Update the Red Hat systems
  ansible.builtin.dnf:
    name:  "*"
    state: latest
  when: ansible_os_family == "RedHat"
