---
- name: Install the latest version of htop, nano, and crictl
  ansible.builtin.dnf:
    name:
      - nano
    state: latest
  when: ansible_os_family == "RedHat"
  tags:
  - user

- name: Remove zram from system
  ansible.builtin.dnf:
    name:
      - zram-generator-defaults
    state: absent
  when: ansible_os_family == "RedHat"
  tags:
  - user

- name: Update the Red Hat systems
  ansible.builtin.dnf:
    name:  "*"
    state: latest
  when: ansible_os_family == "RedHat"
  tags:
  - update
