---
- name: Install the latest version of nano
  ansible.builtin.dnf:
    name:
    - nano
    state: latest

- name: Remove zram from system
  ansible.builtin.dnf:
    name:
    - zram-generator-defaults
    state: absent
  notify:
  - Reboot the systems

- name: Update the Red Hat systems
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
