repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
- repo: https://github.com/adrienverge/yamllint
  rev: v1.27.1
  hooks:
  - id: yamllint
- repo: https://github.com/k8s-at-home/sops-pre-commit
  rev: v2.1.1
  hooks:
  - id: forbid-secrets
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: shellcheck
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
  - id: remove-crlf
  - id: remove-tabs
- repo: https://github.com/sirosen/texthooks
  rev: 0.4.0
  hooks:
  - id: fix-smartquotes
