service_type: agent

config_yaml_contents:
  node-name: "{{ ansible_hostname }}"
  server: "https://{{ round_robin_dns | default(groups['control_plane'][0]) }}:6443"
  token: "{{ token }}"

config_node_yaml_contents:
  node-label:
  - adrp.xyz/purpose=worker
  kubelet-arg:
  - node-status-update-frequency=5s
  - config={{ var_path }}/kublet-config.yml
  - make-iptables-util-chains=true
  - streaming-connection-idle-timeout=5m
  kube-proxy-arg:
  - ipvs-strict-arp=true
