namespace: ascii17
name: kubernetes
version: 1.0.1

readme: README.md

authors:
- Allen Conlon <allen@conlon.dev>

description: Plays for kubernetes

dependencies:
  "kubernetes.core": "2.4.0"

repository: https://github.com/A1994SC/playbooks
issues: https://github.com/A1994SC/playbooks/issues
