---
- name: Set SELinux state
  selinux:
    state: "{{ state | default('disabled') }}"
  when: ansible_os_family == "RedHat"
  register: selinuxstate

- name: Reboot the systems
  ansible.builtin.reboot:
  when: selinuxstate.changed
