---
- name: Git stashing contents of nixos
  shell:
    cmd: git stash
    chdir: "{{ git_path }}"
  tags:
  - nixos
  - git
  - stash

- name: Pull lastest config from github
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ git_path }}"
    update: yes
    version: main
  tags:
  - nixos
  - git
  - config

- name: Dry build config
  ansible.builtin.command:
    argv:
      - "{{ nix_bin_path }}/nixos-rebuild"
      - dry-build
  tags:
  - nixos
  - dry

- name: Switch config
  ansible.builtin.command:
    argv:
      - "{{ nix_bin_path }}/nixos-rebuild"
      - switch
  tags:
  - nixos
  - upgrade

- name: Reboot all machines
  ansible.builtin.reboot:
    reboot_command: "{{ nix_bin_path }}/shutdown -r now"
  tags:
  - reboot