---
- name: Create secrets
  include_tasks:
    file: secrets.yml
  loop: "{{ kubernetes_create_secrets }}"
  when: kubernetes_create_secrets is defined and (kubernetes_create_secrets | length > 0)
  no_log: true
