---
- name: Create "{{ item.namespace }}/{{ item.name }}" secret
  kubernetes.core.k8s:
    context: "{{ kubeconfig_context | default('default') }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
      stringData: "{{ item.stringData }}"
