---
- name: Stop the cockpit service and socket
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: stopped
    enabled: false
    masked: true
  with_items:
  - cockpit.service
  - cockpit.socket

- name: "Removing files"
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
  - /etc/issue.d/cockpit.issue
  - /etc/motd.d/cockpit
