---
- name: "Removing files"
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/issue.d/cockpit.issue
    - /etc/motd.d/cockpit
    - /etc/containerd/config.toml
    - /etc/crio/crio.conf
    - /etc/systemd/system/k3s.service
  when: ansible_os_family == "RedHat"
