all:
  children:
    kubernetes_cluster:
      children:
        control_plane:
          hosts:
            titania-kc1.adrp.xyz:
              ansible_host: 10.2.25.10
            titania-kc2.adrp.xyz:
              ansible_host: 10.2.25.11
            titania-kc3.adrp.xyz:
              ansible_host: 10.2.25.12
        worker_node:
          hosts:
            titania-kw1.adrp.xyz:
              ansible_host: 10.2.25.13
            titania-kw2.adrp.xyz:
              ansible_host: 10.2.25.14
            titania-kw3.adrp.xyz:
              ansible_host: 10.2.25.15
