---
- name: Create k3s service file
  register: k3s_service
  template:
    src: "k3s-{{ service_type | default('agent') }}.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- block:
  - name: Start the k3s service
    ansible.builtin.systemd:
      name: k3s
      daemon_reload: true
      state: started
    when: inventory_hostname in groups['control_plane']
  rescue:
  - name: Recovery block
    debug:
      msg: >
        Had issues starting k3s, see if it the node came up by itself.

- block:
  - name: Start the k3s service
    ansible.builtin.systemd:
      name: k3s
      daemon_reload: true
      state: started
    when: inventory_hostname not in groups['control_plane']
  rescue:
  - name: Recovery block
    debug:
      msg: >
        Had issues starting k3s, see if it the node came up by itself.
